In [12]:
import pandas as pd
#path = "D:\\M Tech\\Internship\\Yoshops\\review_dataset.csv"
df = pd.read_excel("Project_list.xlsx")
df.head()

,Se. No.,Description,Remarks,3,4,5,6,7
0,1,AI recommendation based on the students health...,NaN,maintain the 50 health parameters record and p...,"As of now, no one is maintain the 50 health pa...",50 health parameters records and providing the...,"healthcare institutions, corporates, schools a...","As per best of my knowledge, no one is keeping..."
1,2,"Facial expression, voice, tone, pitch recognet...",NaN,NaN,NaN,NaN,NaN,NaN
2,3,"Personality Prediction System via CV, voice, s...",NaN,NaN,NaN,NaN,NaN,NaN
3,4,Heart Disease Prediction Project,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Identify human emotions through pictures,NaN,NaN,NaN,NaN,NaN,NaN